spring:
  application:
    name: medheadUser
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
security:
  jwt:
    secret-key: b7c01262a701ced188117ae6fdb5082b6be223b73ca24c74d4d4c1bc6966fdb0
    # 1h in millisecond
    expiration-time: 3600000